all : ASM CPU

STK_SRC_DIR = CPU/stack/src/
STK_OBJ_DIR = CPU/stack/obj/
ASM_SRC_DIR = ASM/src/
ASM_OBJ_DIR = ASM/obj/

CC = g++
CFLAGS=-c -Wall

CPU : $(STK_OBJ_DIR)main.o $(STK_OBJ_DIR)stack_funcs.o $(STK_OBJ_DIR)debug_funcs.o 
	@$(CC) $(STK_OBJ_DIR)main.o $(STK_OBJ_DIR)stack_funcs.o $(STK_OBJ_DIR)debug_funcs.o -o CPU_out

$(STK_OBJ_DIR)main.o : $(STK_SRC_DIR)main.cpp
	@$(CC) $(STK_SRC_DIR)main.cpp -c -o $(STK_OBJ_DIR)main.o

$(STK_OBJ_DIR)stack_funcs.o : $(STK_SRC_DIR)stack_funcs.cpp
	@$(CC) $(STK_SRC_DIR)stack_funcs.cpp -c -o $(STK_OBJ_DIR)stack_funcs.o

$(STK_OBJ_DIR)debug_funcs.o : $(STK_SRC_DIR)debug_funcs.cpp
	@$(CC) $(STK_SRC_DIR)debug_funcs.cpp -c -o $(STK_OBJ_DIR)debug_funcs.o
	

ASM: $(ASM_OBJ_DIR)main.o $(ASM_OBJ_DIR)funcs_ASM.o
	@$(CC) $(ASM_OBJ_DIR)main.o $(ASM_OBJ_DIR)funcs_ASM.o -o ASM_out

$(ASM_OBJ_DIR)main.o: $(ASM_SRC_DIR)main.cpp 
	@$(CC) $(ASM_SRC_DIR)main.cpp $(CFLAGS) -o $(ASM_OBJ_DIR)main.o

$(ASM_OBJ_DIR)funcs_ASM.o: $(ASM_SRC_DIR)funcs_ASM.cpp 
	@$(CC) $(ASM_SRC_DIR)funcs_ASM.cpp 	$(CFLAGS) -o $(ASM_OBJ_DIR)funcs_ASM.o

mkdir:
	mkdir $(ASM_OBJ_DIR) -p 
	mkdir $(STK_OBJ_DIR) -p

clean:
	rm $(ASM_OBJ_DIR)*.o *.save ASM_out
	rm $(STK_OBJ_DIR)*.o *.save CPU_out